<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|-------------------------------------------------------------------------- 
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|   http://example.com/
| WARNING: You MUST set this value!
*/
$config['base_url'] = 'http://localhost/portfolio/';

/*
|--------------------------------------------------------------------------
| Index File
|-------------------------------------------------------------------------- 
| Typically this will be your index.php file, unless you've renamed it.
| If you are using mod_rewrite to remove the page set this variable so that it is blank.
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|-------------------------------------------------------------------------- 
| This item determines which server global should be used to retrieve the
| URI string. The default setting of 'REQUEST_URI' works for most servers.
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|-------------------------------------------------------------------------- 
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|-------------------------------------------------------------------------- 
| This determines which set of language files should be used. 
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|-------------------------------------------------------------------------- 
| This determines which character set is used by default in various methods
| that require a character set to be provided.
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|-------------------------------------------------------------------------- 
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).
*/
$config['enable_hooks'] = FALSE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|-------------------------------------------------------------------------- 
| This item allows you to set the filename/classname prefix when extending
| native libraries.
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|-------------------------------------------------------------------------- 
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
*/
$config['composer_autoload'] = FALSE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|-------------------------------------------------------------------------- 
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
*/
// $config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-\(\)';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|-------------------------------------------------------------------------- 
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
*/
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Allow $_GET array
|-------------------------------------------------------------------------- 
| By default CodeIgniter enables access to the $_GET array. 
| If for some reason you would like to disable it, set 'allow_get_array' to FALSE.
*/
$config['allow_get_array'] = TRUE;

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|-------------------------------------------------------------------------- 
| You can enable error logging by setting a threshold over zero. 
| The threshold determines what gets logged.
*/
$config['log_threshold'] = 1; // 1 for error logging

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|-------------------------------------------------------------------------- 
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension
|-------------------------------------------------------------------------- 
| The default filename extension for log files.
| Note: Leaving it blank will default to 'php'.
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|-------------------------------------------------------------------------- 
| The file system permissions to be applied on newly created log files.
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
| integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|-------------------------------------------------------------------------- 
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|-------------------------------------------------------------------------- 
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|-------------------------------------------------------------------------- 
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|-------------------------------------------------------------------------- 
| Whether to take the URL query string into consideration when generating
| output cache files.
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|-------------------------------------------------------------------------- 
| If you use the Encryption class, you must set an encryption key.
*/
$config['encryption_key'] = 'your_encryption_key_here';

/*
|--------------------------------------------------------------------------
| Session Variables
|-------------------------------------------------------------------------- 
| 'sess_driver' = The storage driver to use: files, database, redis, memcached
| 'sess_cookie_name' = The session cookie name
| 'sess_expiration' = The number of SECONDS you want the session to last.
| 'sess_save_path' = The location to save sessions to, driver dependent.
| 'sess_match_ip' = Whether to match the user's IP address when reading the session data.
| 'sess_time_to_update' = How many seconds between CI regenerating the session ID.
| 'sess_regenerate_destroy' = Whether to destroy session data associated with the old session ID
| when auto-regenerating the session ID.
*/
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_samesite'] = 'Lax';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|-------------------------------------------------------------------------- 
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
| 'cookie_samesite' = Cookie's samesite attribute (Lax, Strict or None)
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;
$config['cookie_samesite'] 	= 'Lax';

/*
|--------------------------------------------------------------------------
| Standardize newlines
|-------------------------------------------------------------------------- 
| Determines whether to standardize newline characters in input data.
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|-------------------------------------------------------------------------- 
| Determines whether the XSS filter is always active when GET, POST or COOKIE data is encountered
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|-------------------------------------------------------------------------- 
| Enables a CSRF cookie token to be set. 
*/
$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'csrf_token_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array();
 // You can exclude specific URIs if needed


/*
|--------------------------------------------------------------------------
| Output Compression
|-------------------------------------------------------------------------- 
| Enables Gzip output compression for faster page loads.
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|-------------------------------------------------------------------------- 
| Options are 'local' or any PHP supported timezone.
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|-------------------------------------------------------------------------- 
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly.
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|-------------------------------------------------------------------------- 
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses.
*/
$config['proxy_ips'] = '';
